```yaml
name: Albiceleste
key: Albiceleste
color:blue
emblem: Star_Shine_02
info:
  logo: /llonger13/family-config/IMG-20201123-WA0028__1_-removebg-preview.png
  description: > 
    Mas que un clan, una familia.
    Top 4 Arg. en Wars I 
    Aquí es donde les contendremos
    Aquí es donde nosotros pelearemos
    Y aquí es donde ellos morirán
  social:
    - twitter: http://twitter.com/albicelesteCR
    - discord: https://discord.gg/5Ayk65kWs9
    - twitch: https://www.twitch.tv/albicelestecr
    - facebook: https://facebook.com/albicelesteCR
clans:
  - name: Albiceleste
    tag: LL92RRP
  - name: Albiceleste II
    tag: YGP0GJCC
 
```
